function headers_out = rename_headers(headers_in)

%renames headers into more aesthetic labels for figures/publication
%
%created by Matt Patten
%created on 29/7/2020

attributes_in = {'colour_mean_disk_L','colour_mean_disk_A','colour_mean_disk_B',...
    'colour_primary_trans_L','colour_primary_trans_A','colour_primary_trans_B',...
    'colour_primary_ray_L','colour_primary_ray_A','colour_primary_ray_B',...
    'colour_difference_trans','colour_difference_ray',...
    'colour_slope_disk_L','colour_slope_disk_A','colour_slope_disk_B',...
    'colour_slope_trans_L','colour_slope_trans_A','colour_slope_trans_B',...
    'colour_slope_ray_L','colour_slope_ray_A','colour_slope_ray_B',...
    'gradient_boolean_ray','gradient_boolean_trans',...
    'gradient_position_ray','gradient_position_trans',...
    'gradient_shape_ray','gradient_shape_trans',...
    'size_disk','size_trans','size_ray',...
    'GLCM_Tamura_coarseness','GLCM_Tamura_contrast','GLCM_Tamura_directionality',...
    'NGTDM_coarseness','NGTDM_contrast','NGTDM_complexity',...
    'poll_bullseye','poll_busyness','poll_complexity','poll_depth','poll_pointiness','poll_symmetry'};

attributes_out = {'Colour (L): Disk','Colour (A): Disk','Colour (B): Disk',...
    'Colour (L): Trans','Colour (A): Trans','Colour (B): Trans',...
    'Colour (L): Ray','Colour (A): Ray','Colour (B): Ray',...
    'Colour (LAB) Diff: Trans','Colour (LAB) Diff: Ray',...
    'Colour (L) Slope: Disk','Colour (A) Slope: Disk','Colour (B) Slope: Disk',...
    'Colour (L) Slope: Trans','Colour (A) Slope: Trans','Colour (B) Slope: Trans',...
    'Colour (L) Slope: Ray','Colour (A) Slope: Ray','Colour (B) Slope: Ray',...
    'Gradient (Bool): Ray','Gradient (Bool): Trans',...
    'Gradient Position: Ray','Gradient Position: Trans',...
    'Gradient Shape: Ray','Gradient Shape: Trans',...
    'Size: Disk','Size: Trans','Size: Ray',...
    'Coarseness (GLCM)','Contrast (GLCM)','Directionality (GLCM)',...
    'Coarseness (NGTDM)','Contrast (NGTDM)','Complexity (NGTDM)',...
    'Bullseye (Perceptual)','Busyness (Perceptual)','Complexity (Perceptual)','Depth (Perceptual)','Pointiness (Perceptual)','Symmetry (Perceptual)'};


for i=1:length(headers_in)
    idx = ismember(attributes_in,headers_in(i));
    if any(idx)
        headers_out(i) = attributes_out(idx);
    else
        headers_out(i) = headers_in(i);
    end
end

end